#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/a1f0a08f-c15c-4270-977f-2443e9d44921 # 
title: booksAPI

/books:
  get:
    description: Retrieve a specific book title
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "data": 
                  [
                    {
                      "id": "SbBGk",
                      "title": "Stiff: The Curious Lives of Human Cadavers",
                      "description": null,
                      "datetime": 1341533193,
                      "genre": "science",
                      "author": "Mary Roach",
                      "link": "http://e-bookmobile.com/books/Stiff",
                    },
                    {
                      "id": "werf",
                      "title": "what is happening in the world",
                      "description": null,
                      "datetime": 98765432165,
                      "genre": "fiction",
                      "author": "Levani Robins",
                      "link": "http://e-bookmobile.com/books/Levani",
                    }
                  ],
                "success": true,
                "status": 200
              }
  /{bookTitle}:
    get:
      description: Retrieve a specific book title
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "id": "SbBGk",
                    "title": "Stiff: The Curious Lives of Human Cadavers",
                    "description": null,
                    "datetime": 1341533193,
                    "genre": "science",
                    "author": "Mary Roach",
                    "link": "http://e-bookmobile.com/books/Stiff",
                  },
                  "success": true,
                  "status": 200
                }